### PR TITLE
Milestone 1: Morse decode

### PR DESCRIPTION
**Pull request by Lizdev-05**
In this milestone, we achieved the following...

- Created a method to decode a Morse code character.
- Returned the corresponding character in uppercase.
- Created a method to decode an entire word in Morse code.
- We separated every character in a word by a single space.
- We created a method to decode the entire message in Morse code.
- We separated every character in a word by 3 spaces.

### CODE REVIEW

**Review by GzimAsani — CHANGES_REQUESTED** [review]
### Hello @Lizdev-05 and @Ibizugbe            :wave:   
 Good job so far! There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ## Highlights
 * Good job with the project, the code works as expected :+1:  
 
 ## Required Changes 

- [ ] Please update your Readme file according to your project, use this Microverse [template](https://github.com/microverseinc/readme-template/blob/master/README.md)






 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding! clapclapclap
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lizdev-05** [comment]
Thank you @GzimAsani  for pointing it out. It escaped our minds. We will update it now.

**Review by GzimAsani — APPROVED** [review]
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions
-N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- 

### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Lizdev-05** [comment]
Thank you for reviewing and approving our code.

**Comment by Ibizugbe** [comment]
Thanks alot @Lizdev-05 for implement the required changes, Thanks @GzimAsani  for reviewing  and approving our project.

**Pull request merged**
